@host = http://localhost:3001/api

### Homepage
GET {{host}}/ HTTP/1.1


### Register
POST {{host}}/register HTTP/1.1
content-type: application/json

{
    "email": "p@qq.com",
    "password": "123456",
    "username": "p"
}


### User Info
GET {{host}}/user/q HTTP/1.1


### Users List
GET {{host}}/user/list HTTP/1.1


### Hashed Password Verify
GET {{host}}/verify/654321 HTTP/1.1
